### ISSUE TITLE
Unable to parse BED3 file from Ensembl example

### ISSUE THREAD

**Issue by Benjamin-Lee** [tleonardi/bedparse#13]
I tried using the BED3 file from the [Ensembl example](https://useast.ensembl.org/info/website/upload/bed.html) and am currently getting:

```
(tempenv-19e22026634fb) ~ ❯❯❯ cat test.bed
chr1  213941196  213942363
chr1  213942363  213943530
chr1  213943530  213944697
chr2  158364697  158365864
chr2  158365864  158367031
chr3  127477031  127478198
chr3  127478198  127479365
chr3  127479365  127480532
chr3  127480532  127481699
(tempenv-19e22026634fb) ~ ❯❯❯ bedparse cds test.bed
Traceback (most recent call last):
  File "/Users/BenjaminLee/.virtualenvs/tempenv-19e22026634fb/bin/bedparse", line 10, in <module>
    sys.exit(main())
  File "/Users/BenjaminLee/.virtualenvs/tempenv-19e22026634fb/lib/python3.6/site-packages/bedparse/bedparse.py", line 222, in main
    args.func(args)
  File "/Users/BenjaminLee/.virtualenvs/tempenv-19e22026634fb/lib/python3.6/site-packages/bedparse/bedparse.py", line 40, in cds
    utr=bedline(line.split('\t')).cds(ignoreCDSonly=args.ignoreCDSonly)
  File "/Users/BenjaminLee/.virtualenvs/tempenv-19e22026634fb/lib/python3.6/site-packages/bedparse/bedline.py", line 29, in __init__
    raise BEDexception("Only BED3,4,6,12 are supported. "+self.name+" is neither.")
bedparse.BEDexception: Only BED3,4,6,12 are supported. NoName is neither.
```

Is this behavior anticipated? Either way, could you provide some example files in the repository for experimentation?

**Comment by tleonardi** [comment]
Hi, thanks for testing bedparse!
Yes, this is expected behaviour. I think there are two problems here.

1) Bedparse doesn't seem to recognize that your file is BED3 format. If you have copy-pasted it from the Ensembl website it's possible that the fields are space separated instead of tab separated.
Although the BED specifications allows for whitespace delimited columns (but not in bedDetail files), in my experience they are not widely used or supported, hence my choice to go for tab only.
Having said this, I think it's very common to copy-paste or write BED files by hand, and it can happen to end up with space-separated columns. To get around this problem, I've just added an new subcommand to bedparse ([validateFormat](https://bedparse.readthedocs.io/en/devel/Usage.html#validate-format)) that only does format validation and, optionally, converts "messy" field separators into single tabs.

2. The second problem here is that the CDS command extracts the coding portion of a transcript (i.e. disregards the 5' and 3' UTRs). This information is encoded in the thickStart and thickEnd fields (fields 7 and 8), which are not present in your BED3 file. The strand information is not strictly required, nevertheless I chose to [raise an exception](https://github.com/tleonardi/bedparse/blob/5c4c9fc01ba09c1fbc6cda2b6e3a6c22f31f246d/bedparse/bedline.py#L223) if it's absent, because it makes very little sense to extract the CDS of an unstranded transcript.

Adding examples files is a good idea, I'm working on it now.
Thanks again for your time and effort!

**Comment by tleonardi** [comment]
I've started working on a tutorial, in doc/ (devel branch) there are a tutorial.md and an example.bed.
I'll add more examples and a few screenshot, any feedback is welcome ;)

**Comment by tleonardi** [comment]
Ok, I've completed the [tutorial](https://github.com/tleonardi/bedparse/blob/devel/docs/Tutorial.md).
Let me know if you think it could be made clearer!

**Comment by tleonardi** [comment]
Hi @Benjamin-Lee, did you menage to get the examples to work? Please do let me know if I can help in any way or if you run into problems!
